mixed-port: 7890
allow-lan: true
mode: global
log-level: info
ipv6: false

proxies:
  - name: "BrightData_TW"
    type: http
    server: brd.superproxy.io
    port: 33335
    # 账号必须加引号，且必须带上国家后缀
    username: "brd-customer-hl_739668d7-zone-residential_proxy1-country-tw"
    password: "me6lrg0ysg96"

rules:
  - MATCH,BrightData_TW
