mixed-port: 7890
allow-lan: false
mode: global
log-level: info

proxies:
  - name: "TW-VPS"
    type: ss
    server: "154.223.20.190"
    port: 8388
    cipher: "aes-256-gcm"
    password: "MyStrongPassword123"

rules:
  - MATCH,TW-VPS
