proxies:
  - name: "台湾住宅"
    type: http
    server: brd.superproxy.io
    port: 33335
    username: brd-customer-hl_739668d7-zone-residential_proxy1-country-tw
    password: me6lrg0ysg96

proxy-groups:
  - name: "OFIII-抓取"
    type: select
    proxies:
      - "台湾住宅"
      - DIRECT

rules:
  - DOMAIN-SUFFIX,ofiii.com,OFIII-抓取
  - DOMAIN-SUFFIX,litv.tv,OFIII-抓取
  - MATCH,DIRECT
